[General]
# Gerado por sddm-forge. Editado pela GUI.

backgroundMode=video
background=assets/background.jpeg
backgroundVideo=assets/frieren-moon.mp4
bgColor=#0b0f14
blurRadius=24
videoBlurRadius=4
dimOpacity=0.40
accentColor=#66d9ff
accentColorDim=#55aacc
textColor=#ffffff
subTextColor=#b0c7d8
errorColor=#ff8080
fontFamily=JetBrains Mono
clockFontSize=68
dateFontSize=18
nameFontSize=26
marginX=56
marginY=56
passwordWidth=280
clockFormat=hh:mm
dateFormat=dddd, d 'de' MMMM
dateLocale=pt_BR
inputStyle=underline
buttonStyle=outline
controlStyle=text
controlIcons=off

layoutJson=eyJ2ZXJzaW9uIjoxLCJyb290IjpbeyJpZCI6Im4zMGUwNmQ2NCIsInR5cGUiOiJwYW5lbCIsIm5hbWUiOiJTZXNzw6NvIC8gZW5lcmdpYSIsIm9yaWVudGF0aW9uIjoicm93IiwicG9zaXRpb24iOiJ0b3AtbGVmdCIsIndpZHRoIjoiYXV0byIsImhlaWdodCI6ImF1dG8iLCJhbGlnbiI6ImNlbnRlciIsImp1c3RpZnkiOiJzdGFydCIsImdhcCI6MjYsInBhZGRpbmdYIjowLCJwYWRkaW5nWSI6MCwiYmx1ciI6MCwiZGltIjowLCJ0aW50IjoiIiwibm9pc2UiOjAsImJnIjoiIiwiYm9yZGVyIjoiIiwiYm9yZGVyV2lkdGgiOjEsInJhZGl1cyI6MCwiY2hpbGRyZW4iOlt7ImlkIjoibjJlZTdjZDc1IiwidHlwZSI6InNlc3Npb25CdXR0b24ifSx7ImlkIjoibjYwYzUxNWFhIiwidHlwZSI6InJlYm9vdEJ1dHRvbiJ9LHsiaWQiOiJuOGFiZWJjOTMiLCJ0eXBlIjoicG93ZXJCdXR0b24ifV19LHsiaWQiOiJuMWYzMjUzYzIiLCJ0eXBlIjoicGFuZWwiLCJuYW1lIjoiUmVsw7NnaW8iLCJvcmllbnRhdGlvbiI6ImNvbHVtbiIsInBvc2l0aW9uIjoidG9wLXJpZ2h0Iiwid2lkdGgiOiJhdXRvIiwiaGVpZ2h0IjoiYXV0byIsImFsaWduIjoic3RhcnQiLCJqdXN0aWZ5Ijoic3RhcnQiLCJnYXAiOjQsInBhZGRpbmdYIjowLCJwYWRkaW5nWSI6MCwiYmx1ciI6MCwiZGltIjowLCJ0aW50IjoiIiwibm9pc2UiOjAsImJnIjoiIiwiYm9yZGVyIjoiIiwiYm9yZGVyV2lkdGgiOjEsInJhZGl1cyI6MCwiY2hpbGRyZW4iOlt7ImlkIjoibjViOGE0YWY4IiwidHlwZSI6ImRhdGUifSx7ImlkIjoibmMzY2YxYmRmIiwidHlwZSI6ImNsb2NrIn1dfSx7ImlkIjoibjI2YTZkMmQ4IiwidHlwZSI6InBhbmVsIiwibmFtZSI6IkxvZ2luIiwib3JpZW50YXRpb24iOiJjb2x1bW4iLCJwb3NpdGlvbiI6ImJvdHRvbS1sZWZ0Iiwid2lkdGgiOiJhdXRvIiwiaGVpZ2h0IjoiYXV0byIsImFsaWduIjoic3RhcnQiLCJqdXN0aWZ5Ijoic3RhcnQiLCJnYXAiOjE0LCJwYWRkaW5nWCI6MCwicGFkZGluZ1kiOjAsImJsdXIiOjAsImRpbSI6MCwidGludCI6IiIsIm5vaXNlIjowLCJiZyI6IiIsImJvcmRlciI6IiIsImJvcmRlcldpZHRoIjoxLCJyYWRpdXMiOjAsImNoaWxkcmVuIjpbeyJpZCI6Im41YWY1YmRhMiIsInR5cGUiOiJ1c2VybmFtZVJvdyIsImNhcm91c2VsIjp0cnVlfSx7ImlkIjoibjMzMTEyMjAwIiwidHlwZSI6InVzZXJIYW5kbGUifSx7ImlkIjoibjRiZDc1OTNjIiwidHlwZSI6InBhc3N3b3JkIn0seyJpZCI6Im5jNGRkZTU2MiIsInR5cGUiOiJsb2dpbkJ1dHRvbiJ9LHsiaWQiOiJuOWE4MGY1OTMiLCJ0eXBlIjoiZXJyb3JNZXNzYWdlIn1dfV19
